#!/usr/bin/env node
require('babel-register');
require('babel-polyfill');
const program = require('commander');
const syncService = require('../integrations/services/sync');

program
  .version('0.0.1')
  .option('-e, --execute [task]', 'Execute task')
  .parse(process.argv);

if (!program.execute) {
  console.log('Missing -e attribute to execute task.');
  return;
}

switch (program.execute) {
  case 'sync:networks': {
    console.log('Start syncing networks for integrations.');

    return syncService.syncWithIntegrationPartner()
      .then(() => console.log('Finished syncing networks for integrations.'));
  }
  default:
    console.log('No handler attached to taskname.');
    return;
}
